version: '3.7'

services:
  app:
    build:
      dockerfile: ./.docker/node/Dockerfile
      context: .
    image: injector_node
    volumes:
      - .:/app
      - /app/node_modules
      - ${GIT_SSH_KEY}:/root/.ssh/tmp
    ports:
      - ${PUBLIC_PORT}:8080
    env_file:
      - ./.env
