version: '2'
services:
  injector:
    build:
      dockerfile: ./.docker/node/Dockerfile
      context: .
    image: injector_node
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    ports:
      - ${PUBLIC_PORT}:8080

  puppeteer:
    build:
      dockerfile: ./.docker/puppeteer/Dockerfile
      context: .
    image: injector_puppeteer
    volumes:
      - .:/app
      - node_modules:/app/node_modules/

volumes:
  node_modules:
