version: 2

defaults: &defaults
  working_directory: ~/project/vue-injector
  docker:
    - image: circleci/node:12-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-vue-{{ .Branch }}-
            - v1-vue-
      - run: yarn install
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-injector

  lint-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn lint
      - run: yarn test:types

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test:unit
      - run:
          name: report coverage
          command: |
            if [[ -z $CI_PULL_REQUEST ]]; then
              yarn test:cover
            fi
      
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/project/vue-injector/.npmrc
      - run:
          name: Add types
          command: yarn types
      - run:
          when:
            condition:
              equal: [ master, << pipeline.git.branch >> ]
          name: Publish package
          command: npm publish --tag latest || exit 0
      - run:
          when:
            condition:
              equal: [ next, << pipeline.git.branch >> ]
          name: Publish package
          command: npm publish --tag next || exit 0

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-unit:
          requires:
            - install
      - lint-types:
          requires:
            - install
      - deploy:
          requires:
            - test-unit
            - lint-types
          filters:
            branches:
              only:
                - master
                - next
            tags:
              only: /^v.*/
